module.exports = {
  KICK_PLAYER: "KICK_PLAYER",
  PLAY_CARD: "PLAY_CARD",
  GET_GAMES: "GET_GAMES",
  GET_GAME: "GET_GAME",
  CREATE_GAME: "CREATE_GAME",
  LEAVE_GAME: "LEAVE_GAME",
  DELETE_GAME: "DELETE_GAME",
  JOIN_GAME: "JOIN_GAME",
  START_GAME: "START_GAME",
  TURN_END: "TURN_END",
  DRAW_CARD: "DRAW_CARD",
  CURRENT_PLAYER_UPDATE: "CURRENT_PLAYER_UPDATE"
};
