const MIN_PLAYERS_COUNT = 2;

const ROLES = {
  BUILDER: "BUILDER",
  SABOTEUR: "SABOTEUR"
};

const STATUSES = {
  WAITING_FOR_PLAYERS: "WAITING_FOR_PLAYERS",
  PLAYING: "PLAYING",
  ROUND_END: "ROUND_END",
  COMPLETED: "COMPLETED"
};

const DESTINATION_TYPES = {
  DISCARD: "DISCARD",
  SLOT: "SLOT",
  PLAYER: "PLAYER"
};

module.exports = {
  DESTINATION_TYPES,
  MIN_PLAYERS_COUNT,
  ROLES,
  STATUSES
};
