export default {
  KICK_PLAYER: "KICK_PLAYER",
  PLAY_CARD: "PLAY_CARD",
  GET_GAMES: "GET_GAMES",
  GET_GAME: "GET_GAME",
  CREATE_GAME: "CREATE_GAME",
  LEAVE_GAME: "LEAVE_GAME",
  DELETE_GAME: "DELETE_GAME",
  JOIN_GAME: "JOIN_GAME"
};
